--공통코드
INSERT INTO devchallegers.tb_comn_cd(COM_GRP_CD, COM_CD, CD_NM, CD_DESC, DEFAULT_YN, SORT, DEL_YN, CRE_DT, REG_USER, MOD_DT, MOD_USER)
VALUES('NOTIFICATIONTYPE', 'ZZ', '알림 타입', '알림 타입', 'N', 0, 'N', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP, 'Admin');
INSERT INTO devchallegers.tb_comn_cd(COM_GRP_CD, COM_CD, CD_NM, CD_DESC, DEFAULT_YN, SORT, DEL_YN, CRE_DT, REG_USER, MOD_DT, MOD_USER)
VALUES('NOTIFICATIONTYPE', 'CHALLENGE', '챌린지', '챌린지', 'N', 1, 'N', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP, 'Admin');
INSERT INTO devchallegers.tb_comn_cd(COM_GRP_CD, COM_CD, CD_NM, CD_DESC, DEFAULT_YN, SORT, DEL_YN, CRE_DT, REG_USER, MOD_DT, MOD_USER)
VALUES('NOTIFICATIONTYPE', 'SNS', 'SNS', 'SNS', 'N', 2, 'N', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP, 'Admin');
INSERT INTO devchallegers.tb_comn_cd(COM_GRP_CD, COM_CD, CD_NM, CD_DESC, DEFAULT_YN, SORT, DEL_YN, CRE_DT, REG_USER, MOD_DT, MOD_USER)
VALUES('NOTIFICATIONTYPE', 'TODO', 'TO-DO', 'TO-DO', 'N', 3, 'N', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP, 'Admin');
INSERT INTO devchallegers.tb_comn_cd(COM_GRP_CD, COM_CD, CD_NM, CD_DESC, DEFAULT_YN, SORT, DEL_YN, CRE_DT, REG_USER, MOD_DT, MOD_USER)
VALUES('NOTIFICATIONTYPE', 'FRIEND', '친구 관리', '친구 관리', 'N', 4, 'N', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP, 'Admin');