DROP DATABASE IF EXISTS `devchallegers`;
CREATE SCHEMA `devchallegers` DEFAULT CHARACTER SET utf8mb4 ;

DROP USER IF EXISTS 'chlgadm'@'localhost';
CREATE USER 'chlgadm'@'localhost' identified by 'chlgadm!23';

USE `devchallegers`;

GRANT ALL ON `devchallegers`.* TO 'chlgadm'@'localhost';

DROP TABLE IF EXISTS `devchallegers`.`tb_user_mgmt`;
CREATE TABLE `devchallegers`.`tb_user_mgmt` (
  `USER_ID` VARCHAR(20) NOT NULL,
  `DOMAIN` VARCHAR(50) NULL,
  `USER_NM` VARCHAR(50) NULL,
  `PASSWORD` VARCHAR(50) NULL,
  `LEVEL_OPEN` VARCHAR(1) NULL DEFAULT 'Y',
  `CELL` VARCHAR(20) NULL,
  `DEL_YN` VARCHAR(1) NULL DEFAULT 'N',
  `CRE_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `REG_USER` VARCHAR(20) NULL,
  `MOD_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MOD_USER` VARCHAR(20) NULL,
  PRIMARY KEY (`USER_ID`))
COMMENT = '사용자 관리';

DROP TABLE IF EXISTS `devchallegers`.`tb_friend_mgmt`;
CREATE TABLE `devchallegers`.`tb_friend_mgmt` (
  `USER_ID` VARCHAR(20) NOT NULL,
  `SEQ` INT(3) NOT NULL,
  `FRIEND_ID` VARCHAR(20) NOT NULL,
  `REQ_STATUS` VARCHAR(10) NULL,
  `DEL_YN` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`USER_ID`, `SEQ`))
COMMENT = '친구 관리';

DROP TABLE IF EXISTS `devchallegers`.`tb_challenge_mgmt`;
CREATE TABLE `devchallegers`.`tb_challenge_mgmt` (
  `CHALLENGE_NO` VARCHAR(30) NOT NULL,
  `TITLE` VARCHAR(30) NOT NULL,
  `CONTENTS` VARCHAR(500) NOT NULL,
  `PERIOD_START` DATE NOT NULL,
  `PERIOD_END` DATE NOT NULL,
  `FREQUENCY` VARCHAR(3) NOT NULL,
  `EXAMPLE` VARCHAR(100) NOT NULL,
  `CATEGORY` VARCHAR(10) NULL,
  `TYPE` VARCHAR(5) NULL,
  `MAIN_EXP` VARCHAR(1) NULL,
  `STATUS` VARCHAR(10) NULL,
  PRIMARY KEY (`CHALLENGE_NO`))
COMMENT = '챌린지 관리';

DROP TABLE IF EXISTS `devchallegers`.`tb_challenge_photo`;
CREATE TABLE `devchallegers`.`tb_challenge_photo` (
  `PHOTO_NO` VARCHAR(30) NOT NULL,
  `CHALLENGE_NO` VARCHAR(30) NOT NULL,
  `MAIN_YN` VARCHAR(1) NOT NULL DEFAULT 'N',
  `PHOTO_NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`PHOTO_NO`))
COMMENT = '챌린지 사진';

DROP TABLE IF EXISTS `devchallegers`.`tb_challenge_part`;
CREATE TABLE `devchallegers`.`tb_challenge_part` (
  `PART_NO` VARCHAR(30) NOT NULL,
  `CHALLENGE_NO` VARCHAR(30) NOT NULL,
  `USER_ID` VARCHAR(20) NOT NULL,
  `POINT` INT NULL,
  PRIMARY KEY (`PART_NO`))
COMMENT = '챌린지 배팅';

DROP TABLE IF EXISTS `devchallegers`.`tb_sns_mgmt`;
CREATE TABLE `devchallegers`.`tb_sns_mgmt` (
  `USER_ID` VARCHAR(20) NOT NULL,
  `POST_ID` INT NOT NULL AUTO_INCREMENT,
  `IMAGE_PATH` VARCHAR(50) NULL,
  `STATUS` VARCHAR(1) NULL,
  `DEL_YN` VARCHAR(1) NULL DEFAULT 'N',
  `CRE_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `REG_USER` VARCHAR(20) NULL,
  `MOD_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MOD_USER` VARCHAR(20) NULL,
  PRIMARY KEY (`POST_ID`))
COMMENT = 'SNS 관리';

DROP TABLE IF EXISTS `devchallegers`.`tb_sns_cate`;
CREATE TABLE `devchallegers`.`tb_sns_cate` (
  `POST_ID` INT NOT NULL,
  `SEQ` INT NOT NULL,
  `CATEGORY` VARCHAR(20) NOT NULL,
  `DEL_YN` VARCHAR(1) NULL DEFAULT 'N',
  `CRE_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `REG_USER` VARCHAR(20) NULL,
  `MOD_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MOD_USER` VARCHAR(20) NULL,
  PRIMARY KEY (`POST_ID`, `SEQ`))
COMMENT = 'SNS 카테고리';

DROP TABLE IF EXISTS `devchallegers`.`tb_todo_mgmt`;
CREATE TABLE `devchallegers`.`tb_todo_mgmt` (
  `TODO_ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(50) NOT NULL,
  `EXEC_DT` DATE NOT NULL,
  `DEL_YN` VARCHAR(1) NULL DEFAULT 'N',
  `CRE_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `REG_USER` VARCHAR(20) NULL,
  `MOD_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MOD_USER` VARCHAR(20) NULL,
  PRIMARY KEY (`TODO_ID`))
COMMENT = 'TODO 관리';

DROP TABLE IF EXISTS `devchallegers`.`tb_sns_like`;
CREATE TABLE `devchallegers`.`tb_sns_like` (
  `POST_ID` INT NOT NULL AUTO_INCREMENT,
  `LIKE_USER_ID` VARCHAR(20) NOT NULL,
  `DEL_YN` VARCHAR(1) NULL DEFAULT 'N',
  `CRE_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `REG_USER` VARCHAR(20) NULL,
  `MOD_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MOD_USER` VARCHAR(20) NULL,
  PRIMARY KEY (`POST_ID`, `LIKE_USER_ID`))
COMMENT = 'SNS 좋아요';

DROP TABLE IF EXISTS `devchallegers`.`tb_comn_cd`;
CREATE TABLE `devchallegers`.`tb_comn_cd` (
  `COM_GRP_CD` VARCHAR(20) NOT NULL,
  `COM_CD` VARCHAR(20) NOT NULL,
  `CD_NM` VARCHAR(100) NULL,
  `CD_DESC` VARCHAR(200) NULL,
  `DEFAULT_YN` VARCHAR(1) NULL DEFAULT 'N',
  `SORT` INT NULL,
  `USE_YN` VARCHAR(1) NULL DEFAULT 'Y',
  `DEL_YN` VARCHAR(1) NULL DEFAULT 'N',
  `CRE_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `REG_USER` VARCHAR(20) NULL,
  `MOD_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MOD_USER` VARCHAR(20) NULL,
  PRIMARY KEY (`COM_GRP_CD`, `COM_CD`))
COMMENT = '공통코드 관리';

DROP TABLE IF EXISTS `devchallegers`.`tb_notification_mgmt`;
CREATE TABLE `devchallegers`.`tb_notification_mgmt` (
  `NOTIFICATION_ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(20) NOT NULL,
  `OBJECT_ID` VARCHAR(20) NULL,
  `NOTIFICATION_DT` VARCHAR(20) NOT NULL,
  `MESSAGE` VARCHAR(1000) NULL,
  `CONFRIM_YN` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`NOTIFICATION_ID`))
COMMENT = '알림 관리';

DROP TABLE IF EXISTS `devchallegers`.`tb_challenge_certify`;
CREATE TABLE `devchallegers`.`tb_challenge_certify` (
  `CHALLENGE_NO` VARCHAR(30) NOT NULL,
  `USER_ID` VARCHAR(20) NOT NULL,
  `SEQ` INT(2) NOT NULL,
  `PATH` VARCHAR(50) NULL,
  `CRE_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `REG_USER` VARCHAR(20) NULL,
  `DEL_YN` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`CHALLENGE_NO`, `USER_ID`, `SEQ`))
COMMENT = '챌린지 인증';